Bash scripting
arcus/education_modules pull request #236
Opened 2022-11-16 21:39 UTC by drelliche

As of right now the scripts referenced in this module are in a branch of the learning_bash repo: https://github.com/arcus/learning_bash/tree/scripts 

They will be merged once this module is approved. I have checked their addition doesn't interfere with the other bash modules, but this is also worth a double check.

2022-11-16 21:42 UTC, drelliche commented
@franzenr You seem to be on a Bash roll, but let me know if you don't have bandwidth to QA this and I'll pass it to someone else.

I'm also hoping we will have an intern with a Windows laptop this winter to Windows-test all of these for us...

2022-12-29 01:58 UTC, rosemm commented
I'll nab this one from Rose since she's out of the office for a bit!

2022-12-29 02:13 UTC, rosemm commented on bash_scripts/bash_scripts.md
> +estimated_time: 1 hour
missing `long_description` here

2022-12-29 04:03 UTC, rosemm requested changes
Great module! I found a bunch of little things, but nothing major.

2022-12-29 15:10 UTC, drelliche commented on bash_scripts/bash_scripts.md
> +You might have heard the terms "script" and "bash scripting" and "shell script" used interchangeably. This is probably because the Bash language is most powerful when you use it to write short script
Nope, this is definitely confusing and I will reword/rewrite it! Thanks for the heads up!

2022-12-29 16:22 UTC, drelliche commented on bash_scripts/bash_scripts.md
> +estimated_time: 1 hour
Oops!! added!

2022-12-29 16:24 UTC, drelliche commented on bash_scripts/bash_scripts.md
> +- Write simple Bash scripts
Hmmmm... I went through and capitalized it everywhere it is in a sentence, to see how jarring that would be. Would you take a look at see if "technically correct" is in fact the best form of correct in this case? If not, I can easily change them all back to lowercase unless they start a sentence.

2022-12-29 16:27 UTC, drelliche commented on bash_scripts/bash_scripts.md
> +
added!

2022-12-29 16:36 UTC, drelliche commented on bash_scripts/bash_scripts.md
> +You might have heard the terms "script" and "bash scripting" and "shell script" used interchangeably. This is probably because the Bash language is most powerful when you use it to write short script
I've removed some of this paragraph and folded one sentence into the highlight box after it, which is now a cool-fact box. 

Let me know whether it makes any sense now.

2023-01-04 03:01 UTC, rosemm reviewed
Ah, yes, thank you! I think that's much clearer.

2023-01-04 03:13 UTC, rosemm commented on bash_scripts/bash_scripts.md
> +- Write simple Bash scripts
I don't find it jarring, actually. So I think my inclination would be to capitalize. Although now that I'm looking for it, I notice that we have inconsistent capitalization of "Bash" in the other modules (sigh), e.g. [Bash 101](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/bash_command_line_101/bash_command_line_101.md#1). 
But I vote to deal with that later, and for this module I say you're good.

2023-01-04 03:14 UTC, rosemm approved these changes
This looks good to me!

2023-01-04 03:14 UTC, rosemm commented on bash_scripts/bash_scripts.md
> +You might have heard the terms "script" and "bash scripting" and "shell script" used interchangeably. This is probably because the Bash language is most powerful when you use it to write short script
Love it :)

2023-01-04 03:18 UTC, merged