add less command to bash 101
arcus/education_modules pull request #321
Opened 2023-03-15 17:08 UTC by drelliche

@leemc-data-ed I added the `less` command in addition to `cat`. Please let me know if there is adequate information here to prep learners for eventually using `less` with omics stuff.

Other updates include a little revamp of the "manual" section and making the highlight boxes match the new formatting.

2023-03-20 18:44 UTC, drelliche commented
@leemc-data-ed  and @franzenr I also incorporated some of the suggestions from Issue https://github.com/arcus/education_modules/issues/212 since those also apply to this first bash module.

2023-03-21 20:22 UTC, leemc-data-ed commented
@drelliche working on this now! One thing I noticed as I'm getting started is that the highlight boxes in the Lesson Preparation section still need to be updated.

2023-03-21 20:31 UTC, leemc-data-ed requested changes
I think this is great! I just suggested a couple of changes, but otherwise lgtm!

2023-03-21 20:31 UTC, leemc-data-ed commented on bash_command_line_101/bash_command_line_101.md
>  The command `cat` is very powerful three-part function that allows a reader to view, combine, or create a new version of a file. In fact `cat` is a shortening of the word "con**cat**enate."
I think this could be a good place to link to the manual entry for `cat`, since it does more things than we actually talk about here.

2023-03-22 14:38 UTC, drelliche commented
@leemc-data-ed Suggestions have been incorporated! Let me know if there is anything else needed before merging.

2023-03-22 17:03 UTC, leemc-data-ed approved these changes
Lgtm!

2023-03-22 17:04 UTC, merged