Omics setup
arcus/education_modules pull request #398
Opened 2023-06-25 17:21 UTC by rosemm

Wrapper module for learners to launch the AMI that can then be used for subsequent practical omics modules.

2023-07-20 18:27 UTC, leemc-data-ed requested changes
Just a couple of small things, but I think this is generally good to go!

2023-07-21 16:58 UTC, rosemm commented on genomics_setup/genomics_setup.md
> +docs_version: 1.1.0
Good catch! Thank you!

2023-07-21 16:59 UTC, rosemm commented
Thanks, @leemc-data-ed! I think this is all set now.

2023-07-24 16:13 UTC, leemc-data-ed requested changes
I think this is the last thing, then it should be good to go!

2023-07-24 16:13 UTC, leemc-data-ed commented on genomics_setup/genomics_setup.md
> +version:  0.0.1
```suggestion
version:  1.0.0
```

2023-07-24 20:11 UTC, rosemm commented
Okay, @leemc-data-ed I think this is ready!

2023-07-24 20:30 UTC, leemc-data-ed approved these changes
Lgtm!

2023-07-24 20:33 UTC, merged