update to docs v3
arcus/education_modules pull request #787
Opened 2023-11-07 21:06 UTC by franzenr

resolves #779
resolves #780
resolves #781

brings this module up to alignment with v1-3 of docs

2023-11-15 18:31 UTC, leemc-data-ed requested changes
Just one issue I found with version history, otherwise looks good!

2023-11-15 18:31 UTC, leemc-data-ed commented on directories_and_file_paths/directories_and_file_paths.md
> +@version_history
Version history is not rendering correctly in Liascript for some reason-- but I'm not immediately sure why? The section is visible but the versions and descriptions I see in the raw markdown are different in the rendered page (it looks like sample text). I checked in Chrome and Safari.

2023-11-20 15:56 UTC, rosemm approved these changes
LGTM

2023-11-20 15:59 UTC, rosemm commented
Lol @leemc-data-ed I just realized you and I both had this PR in our jira tickets by mistake --- I thought you were just jumping in and being helpful 😂

2023-11-20 16:02 UTC, leemc-data-ed commented
Haha well better than no one being assigned I guess!

2023-11-20 16:04 UTC, leemc-data-ed approved these changes
LGTM!

2023-11-20 16:04 UTC, leemc-data-ed commented on directories_and_file_paths/directories_and_file_paths.md
> +@version_history
Oooh amazing, thanks for figuring this out!

2023-11-20 16:04 UTC, merged