update to docs v3
arcus/education_modules pull request #792
Opened 2023-11-13 23:44 UTC by franzenr

bring in line with docs v1, v2, and v3.

2023-11-13 23:47 UTC, franzenr commented on git_creation_and_tracking/git_creation_and_tracking.md
> +previous_sequential_module: git_setup_mac_and_linux, git_setup_windows
@drelliche Not sure if having two previous sequential modules listed is acceptable or if it will throw a wrench into any of the discovery app stuff!

2023-11-15 14:53 UTC, franzenr commented on git_creation_and_tracking/git_creation_and_tracking.md
> +previous_sequential_module: git_setup_mac_and_linux, git_setup_windows
verbal convo with Elizabeth right now confirmed that this is fine!

2023-11-20 20:30 UTC, rosemm requested changes
Looks great! One little typo in the metadata, and then I think we're good to go :)

2023-11-20 23:00 UTC, franzenr commented
Wonderful, thanks for the great attention to detail, @rosemm! We should be good to merge this in once it has your official stamp of approval!

2023-11-20 23:24 UTC, rosemm approved these changes
Lgtm!

2023-11-20 23:24 UTC, merged