Demystifying api
arcus/education_modules pull request #887
Opened 2024-01-31 17:51 UTC by pm0kjp

2024-03-22 14:26 UTC, leemc-data-ed commented
https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/demystifying-api/demystifying_apis/demystifying_apis.md#1

2024-03-22 18:43 UTC, leemc-data-ed requested changes
Just a few small things, but I think this is awesome!

2024-03-22 18:43 UTC, leemc-data-ed commented on demystifying_apis/demystifying_apis.md
> +The United States Office of the National Coordinator for Health Information Technology (ONC) is driving an effort to develop and standardize APIs related to electronic health information.  Read more
```suggestion
If you're interested in reading more about APIs in the biomedical and healthcare spaces, [the United States Office of the National Coordinator for Health Information Technology (ONC) is driving an effort to develop and standardize APIs related to electronic health information](https://www.healthit.gov/topic/scientific-initiatives/accelerating-apis-scientific-discovery). 
```
This is just a suggestion to try to make the link text itself a bit more descriptive, but I don't have super strong feelings about it.

2024-03-22 18:43 UTC, leemc-data-ed commented on demystifying_apis/demystifying_apis.md
> +![Six lines of Python code which get all of the records from a REDCap database ](media/pycap.png)
```suggestion
![Six lines of Python code which get all of the records from a REDCap database.](media/pycap.png)
```

2024-03-22 18:43 UTC, leemc-data-ed commented on demystifying_apis/demystifying_apis.md
> +You'll use your computer to send a message to the server asking for whatever you need from the API.  Then the server will send back some combination of a return code (such as 200, good, or 404, not f
```suggestion
You'll use your computer to send a message to the server asking for whatever you need from the API.  Then the server will send back some combination of a return code (such as 200, "good", or 404, "not found") and, if things went well, the data you requested in your message.
```

2024-03-22 18:43 UTC, leemc-data-ed commented on demystifying_apis/demystifying_apis.md
> +Note that there are some terms added in the URL, parameters like `db` and `term`.  There are clearly some rules about how `term` is structured, and if we wanted to learn more about this API we could
```suggestion
Note that there are some terms that are included in the URL, parameters like `db` and `term`.  There are clearly some rules about how `term` is structured, and if we wanted to learn more about this API we could read their documentation to learn what parameters we could include in the URL.
```

2024-03-22 18:43 UTC, leemc-data-ed commented on demystifying_apis/demystifying_apis.md
> +Entrez, like many APIs, has a limit to what you can do anonymously.  If you try to run this a few times in a row, you'll get an error message that starts with `{"error":"API rate limit exceeded"`...
```suggestion
E-utilities, like many APIs, has a limit to what you can do anonymously.  If you try to run this a few times in a row, you'll get an error message that starts with `{"error":"API rate limit exceeded"`...
```

2024-03-25 14:58 UTC, pm0kjp commented on demystifying_apis/demystifying_apis.md
> +
I agree!  Adding in a new commit.

2024-03-25 17:17 UTC, pm0kjp commented
ok @leemc-data-ed I think we're square?  I added your suggestions and added a smidge of metadata that you recommended as well!

2024-03-25 17:28 UTC, merged